/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Hello__factory } from "./Hello__factory";
export { HelloStorage__factory } from "./HelloStorage__factory";
