/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helloSol from "./hello.sol";
export type { helloSol };
import type * as helloV2Sol from "./helloV2.sol";
export type { helloV2Sol };
export * as factories from "./factories";
export type { Hello } from "./hello.sol/Hello";
export { Hello__factory } from "./factories/hello.sol/Hello__factory";
export type { HelloStorage } from "./hello.sol/HelloStorage";
export { HelloStorage__factory } from "./factories/hello.sol/HelloStorage__factory";
export type { HelloV2Storage } from "./helloV2.sol/HelloV2Storage";
export { HelloV2Storage__factory } from "./factories/helloV2.sol/HelloV2Storage__factory";
