/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Hello__factory } from "./Hello__factory";
export { HelloV2Storage__factory } from "./HelloV2Storage__factory";
